### ISSUE TITLE
What's the relationship with MarkdownX?

### ISSUE THREAD

**Issue by chuxubank** [qinci/MarkdownEditors#21]
[MarkdownX](https://github.com/Ryeeeeee/MarkdownX)
Yours apps are too similar lol.

**Comment by qinci** [comment]
Please see the README 
<img width="458" alt="2017-12-30 4 01 27" src="https://user-images.githubusercontent.com/16683610/34452468-c91825de-ed7a-11e7-8348-36c16feda382.png">
