### ISSUE TITLE
我想点击存在的文本进去应该显示预览状态

### ISSUE THREAD

**Issue by mikedream89** [qinci/MarkdownEditors#4]
点击存在的文本我想进入预览状态会更好，因为，如果插入图片，在编辑状态下是无法查看图片的内容，一般点击文本先预览，然后应该有个编辑按钮可以点，
这个是我个人建议

**Comment by qinci** [comment]
目前左右滑动切换编辑和预览（编辑左滑是预览界面，预览界面右滑是编辑界面，也可以选择编辑和预览的菜单），已经存在的文件进去默认是预览这种情况代码已经写了，但是被我注释了，有一点问题，我后面会做成这个效果
