### ISSUE TITLE
编辑时召唤不出工具栏

### ISSUE THREAD

**Issue by 491134648** [qinci/MarkdownEditors#5]
qinci：
  你好，安装app后编辑时召唤不出工具栏，
  机型信息 
  红米2a android  4.4.4 miui 7.3
![截图](https://cloud.githubusercontent.com/assets/9816794/16641567/85254f14-4434-11e6-8c06-5f822b8461d2.png)

**Comment by qinci** [comment]
谢谢你的反馈

**Comment by ss518926** [comment]
好像是界面还没写，view_edit_operate里面就只有一个TextView，而且工具栏所用到的那些图片资源都还没使用。

**Comment by xiang9311** [comment]
**换个姿势试试**

**Comment by 491134648** [comment]
怎么换？

**Comment by jjdxmashl** [comment]
同样的问题，红米note 4.4.4版本，也是召唤不出来

**Comment by zhongzilu** [comment]
**解决办法**
把`activity_editor.xml`中的`ExpandableLinearLayout`组放到`ViewPager`下面即可
